### ISSUE TITLE
"Bigger Pouch" Card Inconsistency

### ISSUE THREAD

**Issue by mtnbikegamer** [oliveman521/We-Wizards-Three#2] opened 2024-04-11 15:17 UTC
The thing that adds five recourses only works 50% of the time.

**Comment by oliveman521** [comment] 2024-04-11 20:40
Cannot reproduce either in current project or in release 0.6.0.

**Comment by oliveman521** [comment] 2024-04-30 00:02
Bug was due to the code that checks for passive abilities accidentally clearing one-off abilities on every check, rather than only on checks that are met. Fixed in 0.6.3

**Closed as completed by oliveman521** 2024-04-30 00:02 UTC
